### ISSUE TITLE
Why do you parse HTML pages?

### ISSUE THREAD

**Issue by bogem** [gazay/ids_please#15]
I can't understand: why do you parse HTML pages from social networks instead of using API to grab information?
All hidden information in social network pages contains in API responses.
Using API much faster and easier to code.
Sorry, if I don't understand project's philosophy, but I read README several times and tried to understand it :(

**Comment by gazay** [comment]
The reason is that to get all information for some account through API you need to know it's internal id in this network. And for most methods – access token, received in a moment when your user authorizes your application. But what if you have only your access token and link to someone's profile? You can just use ids_please to get an internal id and use it in public API methods with your access token to get his feed for example. Or you don't have to have your own application at all to make requests to social network and just get info from parsing HTML page in a unified way from any social network ids_please knows how to grab.

**Comment by bogem** [comment]
Ok. I'm understood :+1: 
Wait for PRs 😉

**Comment by gazay** [comment]
Also, if you can help me with clarifying readme – it would be great. Maybe we need to provide some clear examples

**Comment by bogem** [comment]
Yes, I'll try.
I had this question, because AFAIK for all information, which your app grabs, there is no need access token. Also, by passing link to social network's API, it's available to get this information

**Comment by gazay** [comment]
for example:
https://instagram.com/developer/endpoints/users/#get_users you need an ID and access token
https://developers.facebook.com/docs/graph-api/reference/user - you should have an ID and access_token (http://graph.facebook.com/v2.4/1322232597)
https://vk.com/dev/users.get - you should have an ID or screen name that can be parsed from a link but you'll receive not full info, just full name and id.
etc..

Of course with some social networks, you can work writing own small scripts. But why if there is a small gem without a lot of dependencies which doing the same stuff in one way for many social networks? You just feed it with array of links and get all information

**Comment by bogem** [comment]
Ok. I didn't work with Instagram and FB APIs and don't know about it
And I'm agree with you about a lot of rubygems' dependencies
I have thoughts how I can clarify it in README.
